# the image names comprising the server are
#   cyberdojofoundation/nginx:latest
#   cyberdojofoundation/web:${DOCKER_VERSION}
# if these change the upgrade command in
# cyber-dojo.rb will also need to be changed.

nginx:
  image: cyberdojofoundation/nginx
  container_name: cdf-nginx
  links:
    - "web:cyberdojo_web"
  ports:
    - "80:80"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  user: cyber-dojo
  image: cyberdojofoundation/web:${DOCKER_VERSION}
  container_name: cdf-web
  command: rails server --environment=development
  environment:
    - CYBER_DOJO_SHELL_CLASS=HostShell
    - CYBER_DOJO_DISK_CLASS=HostDisk
    - CYBER_DOJO_LOG_CLASS=StdoutLog
    - CYBER_DOJO_GIT_CLASS=HostGit
    - CYBER_DOJO_LANGUAGES_ROOT=${CYBER_DOJO_HOME}/app/languages
    - CYBER_DOJO_EXERCISES_ROOT=${CYBER_DOJO_HOME}/app/exercises
    - CYBER_DOJO_KATAS_CLASS
    - CYBER_DOJO_KATAS_ROOT
    - CYBER_DOJO_RUNNER_CLASS
    - CYBER_DOJO_RUNNER_SUDO
    - CYBER_DOJO_RUNNER_TIMEOUT
  ports:
    - "3000:3000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
    - cdf-katas-DATA-CONTAINER:rw
